name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        node-version: [18.x]

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TEST_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
      TEST_FIREBASE_EMAIL: ${{ secrets.TEST_FIREBASE_EMAIL }}
      TEST_FIREBASE_PASSWORD: ${{ secrets.TEST_FIREBASE_PASSWORD }}
      TEST_FIREBASE_UID: ${{ secrets.TEST_FIREBASE_UID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root + workspace dependencies
        run: npm install

      - name: Run backend tests
        run: npm --workspace backend run test
