name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TEST_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
      TEST_FIREBASE_EMAIL: ${{ secrets.TEST_FIREBASE_EMAIL }}
      TEST_FIREBASE_PASSWORD: ${{ secrets.TEST_FIREBASE_PASSWORD }}
      TEST_FIREBASE_UID: ${{ secrets.TEST_FIREBASE_UID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root + workspace dependencies
        run: npm install

      - name: Run backend tests
        run: npm --workspace backend run test
